import { Open_Sans } from "next/font/google";
import "./globals.scss";
import "./reset.scss";
const openSans = Open_Sans({ subsets: ["latin"], display: 'swap', });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={openSans.className}>
      <body>{children}</body>
    </html>
  );
}
